Repository DataDog/dd-sdk-ios, pull requests merged in 2025-04, with the labels that each got.

#2248 fix: License check failure
  tools/license/check-license.sh
Labels: mergequeue-status: in_progress

#2246 Merge `hotfix/2.24.1` to `develop`
  BenchmarkTests/Benchmarks/Package.swift
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  DatadogAlamofireExtension.podspec
  DatadogCore.podspec
  DatadogCore/Sources/Versioning.swift
  DatadogCrashReporting.podspec
  DatadogInternal.podspec
  DatadogLogs.podspec
  DatadogObjc.podspec
  DatadogRUM.podspec
  DatadogSessionReplay.podspec
  DatadogTrace.podspec
  DatadogWebViewTracking.podspec
  Package.swift
  SmokeTests/cocoapods/Podfile.src
  TestUtilities.podspec
Labels: mergequeue-status: rejected

#2249 fix: Benchmark CatalogUIKit Storyboards
  BenchmarkTests/CatalogUIKit/Base.lproj/ActivityIndicatorViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/AlertControllerViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/ButtonViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/ColorPickerViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/CustomPageControlViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/CustomSearchBarViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/CustomToolbarViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/DatePickerController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/DefaultPageControlViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/DefaultSearchBarViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/DefaultToolbarViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/FontPickerViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/ImagePickerViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/ImageViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/Main.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/MenuButtonViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/PickerViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/PointerInteractionButtonViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/ProgressViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/SegmentedControlViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/SliderViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/StackViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/StepperViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/SwitchViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/SymbolViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/TextFieldViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/TextViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/TintedToolbarViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/VisualEffectViewController.storyboard
  BenchmarkTests/CatalogUIKit/Base.lproj/WebViewController.storyboard
Labels: mergequeue-status: done

#2250 Fix linter errors on benchmark
  .gitlab-ci.yml
  BenchmarkTests/Runner/Scenarios/RUM/RUMAuto/Core/RickMortyService.swift
  BenchmarkTests/Runner/Scenarios/RUM/RUMAuto/RUMAutoScenario.swift
  BenchmarkTests/Runner/Scenarios/RUM/RUMAuto/UI/EpisodeDetailViewController.swift
  BenchmarkTests/Runner/Scenarios/RUM/RUMAuto/UI/Episodes/EpisodeDetailViewController.swift
  BenchmarkTests/Runner/Scenarios/RUM/RUMAuto/UI/Locations/LocationDetailViewController.swift
  BenchmarkTests/Runner/Scenarios/RUM/RUMAuto/UI/Locations/LocationsViewController.swift
  BenchmarkTests/Runner/Scenarios/RUM/RUMAuto/UI/Shared/CharacterCollectionViewCell.swift
Labels: mergequeue-status: in_progress

#2251 RUMS-4235 Remove `-allow-internal-distribution` flag to framework build script
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  tools/release/build-xcframeworks.sh
Labels: mergequeue-status: in_progress

#2255 Merge release/2.25.0 to develop
  CHANGELOG.md
  DatadogAlamofireExtension.podspec
  DatadogCore.podspec
  DatadogCore/Sources/Versioning.swift
  DatadogCrashReporting.podspec
  DatadogInternal.podspec
  DatadogLogs.podspec
  DatadogObjc.podspec
  DatadogRUM.podspec
  DatadogSessionReplay.podspec
  DatadogTrace.podspec
  DatadogWebViewTracking.podspec
  TestUtilities.podspec
Labels: mergequeue-status: in_progress

#2260 RUM-9395 fix: Fatal App Hang Duplicates
  CHANGELOG.md
  DatadogRUM/Sources/Instrumentation/AppHangs/FatalAppHangsHandler.swift
  DatadogRUM/Tests/Instrumentation/AppHangs/AppHangsMonitorTests.swift
Labels: mergequeue-status: in_progress

#2264 Merge `release/2.26.0` to `develop`
  CHANGELOG.md
  DatadogAlamofireExtension.podspec
  DatadogCore.podspec
  DatadogCore/Sources/Versioning.swift
  DatadogCrashReporting.podspec
  DatadogInternal.podspec
  DatadogLogs.podspec
  DatadogObjc.podspec
  DatadogRUM.podspec
  DatadogSessionReplay.podspec
  DatadogTrace.podspec
  DatadogWebViewTracking.podspec
  TestUtilities.podspec
Labels: mergequeue-status: in_progress

#2270 RUM-9525 Generate Model Initializers
  DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
  DatadogRUM/Sources/DataModels/RUMDataModels.swift
  DatadogRUM/Sources/RUMEvent/RUMOperatingSystemInfo.swift
  DatadogSessionReplay/Sources/Models/SRDataModels.swift
  tools/lint/tests.swiftlint.yml
  tools/rum-models-generator/Sources/CodeGeneration/Print/SwiftPrinter.swift
  tools/rum-models-generator/Sources/rum-models-generator/GenerateRUMModels.swift
  tools/rum-models-generator/Sources/rum-models-generator/GenerateSRModels.swift
  tools/rum-models-generator/Tests/CodeGenerationTests/Print/ObjcInteropPrinterTests.swift
  tools/rum-models-generator/Tests/CodeGenerationTests/Print/SwiftPrinterTests.swift
Labels: mergequeue-status: in_progress

#2272 RUM-9521 Move RUM models to DatadogInternal
  Datadog/Datadog.xcodeproj/project.pbxproj
  DatadogCore/Tests/DatadogObjc/DDRUMConfigurationTests.swift
  DatadogCore/Tests/DatadogObjc/RUM/RUMDataModels+objcTests.swift
  DatadogInternal/Sources/Models/RUM/RUMDataModels.swift
  DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
  DatadogRUM/Sources/RUMConfiguration.swift
  DatadogRUM/Sources/RUMContext/RUMContext.swift
  DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMocks.swift
  DatadogRUM/Tests/RUMEvent/RUMEventBuilderTests.swift
  DatadogRUM/Tests/SDKMetrics/SessionEndedMetricControllerTests.swift
  DatadogRUM/Tests/SDKMetrics/SessionEndedMetricTests.swift
  IntegrationTests/IntegrationScenarios/UITestsHelpers.swift
  IntegrationTests/IntegrationTests.xcodeproj/project.pbxproj
  TestUtilities/Sources/Matchers/RUMSessionMatcher.swift
  TestUtilities/Sources/Mocks/DatadogInternal/RUMDataModelMocks.swift
  TestUtilities/Sources/Mocks/DatadogRUM/RUMFeatureMocks.swift
  tools/rum-models-generator/Sources/rum-models-generator/GenerateRUMModels.swift
  tools/rum-models-generator/run.py
Labels: mergequeue-status: in_progress

#2280 Remove Bitrise files since we migrated to Gitlab
  tools/nightly-unit-tests/.gitignore
  tools/nightly-unit-tests/Makefile
  tools/nightly-unit-tests/bitrise-nightly-unit-tests.yml
  tools/nightly-unit-tests/bitrise.yml.src
  tools/nightly-unit-tests/generate_bitrise_yml.py
  tools/nightly-unit-tests/requirements.txt
  tools/nightly-unit-tests/src/bitrise_yml_writter.py
  tools/nightly-unit-tests/src/devices_parser.py
  tools/nightly-unit-tests/src/runtimes_parser.py
  tools/nightly-unit-tests/src/semver.py
  tools/nightly-unit-tests/src/simulators_parser.py
  tools/nightly-unit-tests/src/test_plan.py
  tools/nightly-unit-tests/src/utils.py
  tools/nightly-unit-tests/tests/__init__.py
  tools/nightly-unit-tests/tests/test_semver.py
  tools/nightly-unit-tests/tests/test_simulators_parser.py
Labels: mergequeue-status: in_progress
