Repository DataDog/dd-sdk-ios, pull requests merged in 2025-01, with the labels that each got.

#2166 Merge `release/2.22.0` to `develop`
  DatadogAlamofireExtension.podspec
  DatadogCore.podspec
  DatadogCore/Sources/Versioning.swift
  DatadogCrashReporting.podspec
  DatadogInternal.podspec
  DatadogLogs.podspec
  DatadogObjc.podspec
  DatadogRUM.podspec
  DatadogSessionReplay.podspec
  DatadogTrace.podspec
  DatadogWebViewTracking.podspec
  TestUtilities.podspec
Labels: mergequeue-status: in_progress

#2156 [MOB-4625] Update `DogfoodingConfig.swift` path
  tools/dogfooding/dogfood.sh
Labels: mergequeue-status: removed

#2164 [APMTI-2602] Move the agent_psr from the root of the span to the metrics map
  DatadogCore/Tests/Datadog/TracerTests.swift
  DatadogCore/Tests/Matchers/SpanMatcher.swift
  DatadogTrace/Sources/Span/SpanEventEncoder.swift
Labels: mergequeue-status: error

#2169 RUM-7937 [SR] Use Deterministic Random Wireframe ID
  Datadog/Datadog.xcodeproj/project.pbxproj
  DatadogSessionReplay/Sources/Recorder/Utilities/Int64+SessionReplay.swift
  DatadogSessionReplay/Sources/Recorder/Utilities/Xoshiro.swift
  DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/SwiftUIWireframesBuilder.swift
  DatadogSessionReplay/Tests/Utilities/XoshiroTests.swift
Labels: mergequeue-status: in_progress

#2171 [Benchmarks] fix: Wrong bundle in SwiftUI scenario
  BenchmarkTests/SwiftUICatalog/Views/Sections/View Modifiers/EffectsModifiersView.swift
Labels: mergequeue-status: in_progress

#2170 RUM-7936 [SR] Fix SwiftUI Placeholder with Feature Flag
  CHANGELOG.md
  DatadogCore/Tests/Datadog/Utils/SwiftUIExtensionsTests.swift
  DatadogCore/Tests/Datadog/Utils/UIKitExtensionsTests.swift
  DatadogInternal/Sources/Utils/SwiftExtensions.swift
  DatadogRUM/Sources/Instrumentation/Views/UIKit/UIKitRUMViewsPredicate.swift
  DatadogRUM/Sources/Utils/SwiftUIExtensions.swift
  DatadogRUM/Sources/Utils/UIKitExtensions.swift
  DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecordingContext.swift
  DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/SwiftUIWireframesBuilderTests.swift
  DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorderTests.swift
  DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorderTests.swift
  DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecordingContextTests.swift
Labels: mergequeue-status: in_progress
